config/routes.rb
Rails.application.routes.draw do
  resources :patients
  resources :patient_cards
  resources :specializations
  resources :departments
  resources :doctors
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/patient_card.rb
class PatientCard < ApplicationRecord
  belongs_to :patient
  validates :diagnosis, presence: true
end

app/controllers/patient_cards_controller.rb
class PatientCardsController < ApplicationController
  before_action :set_patient_card, only: %i[ show edit update destroy ]

  # GET /patient_cards or /patient_cards.json
  def index
    @patient_cards = PatientCard.all
  end

  # GET /patient_cards/1 or /patient_cards/1.json
  def show
  end

  # GET /patient_cards/new
  def new
    @patient_card = PatientCard.new
  end

  # GET /patient_cards/1/edit
  def edit
  end

  # POST /patient_cards or /patient_cards.json
  def create
    @patient_card = PatientCard.new(patient_card_params)

    respond_to do |format|
      if @patient_card.save
        format.html { redirect_to patient_card_url(@patient_card), notice: "Patient card was successfully created." }
        format.json { render :show, status: :created, location: @patient_card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patient_cards/1 or /patient_cards/1.json
  def update
    respond_to do |format|
      if @patient_card.update(patient_card_params)
        format.html { redirect_to patient_card_url(@patient_card), notice: "Patient card was successfully updated." }
        format.json { render :show, status: :ok, location: @patient_card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patient_cards/1 or /patient_cards/1.json
  def destroy
    @patient_card.destroy

    respond_to do |format|
      format.html { redirect_to patient_cards_url, notice: "Patient card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient_card
      @patient_card = PatientCard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_card_params
      params.require(:patient_card).permit(:date)
    end
end

app/helpers/patient_cards_helper.rb
module PatientCardsHelper
end

app/views/patient_cards/_form.html.erb
<%= form_with(model: patient_card) do |form| %>
  <% if patient_card.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(patient_card.errors.count, "error") %> prohibited this patient_card from being saved:</h2>

      <ul>
        <% patient_card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.datetime_field :date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/patient_cards/_patient_card.html.erb
<div id="<%= dom_id patient_card %>">
  <p>
    <strong>Date:</strong>
    <%= patient_card.date %>
  </p>

</div>

app/views/patient_cards/edit.html.erb
<h1>Editing patient card</h1>

<%= render "form", patient_card: @patient_card %>

<br>

<div>
  <%= link_to "Show this patient card", @patient_card %> |
  <%= link_to "Back to patient cards", patient_cards_path %>
</div>

app/views/patient_cards/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Patient cards</h1>

<div id="patient_cards">
  <% @patient_cards.each do |patient_card| %>
    <%= render patient_card %>
    <p>
      <%= link_to "Show this patient card", patient_card %>
    </p>
  <% end %>
</div>

<%= link_to "New patient card", new_patient_card_path %>

app/views/patient_cards/new.html.erb
<h1>New patient card</h1>

<%= render "form", patient_card: @patient_card %>

<br>

<div>
  <%= link_to "Back to patient cards", patient_cards_path %>
</div>

app/views/patient_cards/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @patient_card %>

<div>
  <%= link_to "Edit this patient card", edit_patient_card_path(@patient_card) %> |
  <%= link_to "Back to patient cards", patient_cards_path %>

  <%= button_to "Destroy this patient card", @patient_card, method: :delete %>
</div>