config/routes.rb
Rails.application.routes.draw do
  resources :patients
  resources :patient_cards
  resources :specializations
  resources :departments
  resources :doctors
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/specialization.rb
class Specialization < ApplicationRecord
  belongs_to :doctor
  validates :name, presence: true
end

app/controllers/specializations_controller.rb
class SpecializationsController < ApplicationController
  before_action :set_specialization, only: %i[ show edit update destroy ]

  # GET /specializations or /specializations.json
  def index
    @specializations = Specialization.all
  end

  # GET /specializations/1 or /specializations/1.json
  def show
  end

  # GET /specializations/new
  def new
    @specialization = Specialization.new
  end

  # GET /specializations/1/edit
  def edit
  end

  # POST /specializations or /specializations.json
  def create
    @specialization = Specialization.new(specialization_params)

    respond_to do |format|
      if @specialization.save
        format.html { redirect_to specialization_url(@specialization), notice: "Specialization was successfully created." }
        format.json { render :show, status: :created, location: @specialization }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @specialization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /specializations/1 or /specializations/1.json
  def update
    respond_to do |format|
      if @specialization.update(specialization_params)
        format.html { redirect_to specialization_url(@specialization), notice: "Specialization was successfully updated." }
        format.json { render :show, status: :ok, location: @specialization }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @specialization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specializations/1 or /specializations/1.json
  def destroy
    @specialization.destroy

    respond_to do |format|
      format.html { redirect_to specializations_url, notice: "Specialization was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_specialization
      @specialization = Specialization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def specialization_params
      params.require(:specialization).permit(:name)
    end
end

app/helpers/specializations_helper.rb
module SpecializationsHelper
end

app/views/specializations/_form.html.erb
<%= form_with(model: specialization) do |form| %>
  <% if specialization.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(specialization.errors.count, "error") %> prohibited this specialization from being saved:</h2>

      <ul>
        <% specialization.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/specializations/_specialization.html.erb
<div id="<%= dom_id specialization %>">
  <p>
    <strong>Name:</strong>
    <%= specialization.name %>
  </p>

</div>

app/views/specializations/edit.html.erb
<h1>Editing specialization</h1>

<%= render "form", specialization: @specialization %>

<br>

<div>
  <%= link_to "Show this specialization", @specialization %> |
  <%= link_to "Back to specializations", specializations_path %>
</div>

app/views/specializations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Specializations</h1>

<div id="specializations">
  <% @specializations.each do |specialization| %>
    <%= render specialization %>
    <p>
      <%= link_to "Show this specialization", specialization %>
    </p>
  <% end %>
</div>

<%= link_to "New specialization", new_specialization_path %>

app/views/specializations/new.html.erb
<h1>New specialization</h1>

<%= render "form", specialization: @specialization %>

<br>

<div>
  <%= link_to "Back to specializations", specializations_path %>
</div>

app/views/specializations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @specialization %>

<div>
  <%= link_to "Edit this specialization", edit_specialization_path(@specialization) %> |
  <%= link_to "Back to specializations", specializations_path %>

  <%= button_to "Destroy this specialization", @specialization, method: :delete %>
</div>