config/routes.rb
Rails.application.routes.draw do
  resources :patients
  resources :patient_cards
  resources :specializations
  resources :departments
  resources :doctors
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :department
  has_one :specialization, dependent: :destroy
  validates :name, presence: true
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: %i[ show edit update destroy ]

  # GET /doctors or /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1 or /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors or /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to doctor_url(@doctor), notice: "Doctor was successfully created." }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1 or /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to doctor_url(@doctor), notice: "Doctor was successfully updated." }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1 or /doctors/1.json
  def destroy
    @doctor.destroy

    respond_to do |format|
      format.html { redirect_to doctors_url, notice: "Doctor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def doctor_params
      params.require(:doctor).permit(:name, :specialization)
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_doctor.html.erb
<div id="<%= dom_id doctor %>">
  <p>
    <strong>Name:</strong>
    <%= doctor.name %>
  </p>

  <p>
    <strong>Specialization:</strong>
    <%= doctor.specialization %>
  </p>

</div>

app/views/doctors/_form.html.erb
<%= form_with(model: doctor) do |form| %>
  <% if doctor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
        <% doctor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :specialization, style: "display: block" %>
    <%= form.text_field :specialization %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing doctor</h1>

<%= render "form", doctor: @doctor %>

<br>

<div>
  <%= link_to "Show this doctor", @doctor %> |
  <%= link_to "Back to doctors", doctors_path %>
</div>

app/views/doctors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Doctors</h1>

<div id="doctors">
  <% @doctors.each do |doctor| %>
    <%= render doctor %>
    <p>
      <%= link_to "Show this doctor", doctor %>
    </p>
  <% end %>
</div>

<%= link_to "New doctor", new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New doctor</h1>

<%= render "form", doctor: @doctor %>

<br>

<div>
  <%= link_to "Back to doctors", doctors_path %>
</div>

app/views/doctors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @doctor %>

<div>
  <%= link_to "Edit this doctor", edit_doctor_path(@doctor) %> |
  <%= link_to "Back to doctors", doctors_path %>

  <%= button_to "Destroy this doctor", @doctor, method: :delete %>
</div>